app:
  mode: debug
  port: 9527
db:
  host: 127.0.0.1
  port: 5432
  dbname: mikit_db
  passwd: qazwsx123456
  username: postgres
  max_conns: 10
  max_idle: 5
  max_open: 5
  log_level: 1
redis:
  broker: 127.0.0.1/0
  backend: 127.0.0.1/1
log:
  path: /tmp/mikit/mikit.log
  level: 0
